In [1]:
# from google.colab import drive
# drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [2]:
import numpy as np

In [3]:
folder_location = '/content/gdrive/MyDrive/hw1/data/AwA_python/'

In [4]:
X_seen = np.load(folder_location+'X_seen.npy',encoding='bytes',allow_pickle=True)
X_test = np.load(folder_location+'Xtest.npy',encoding='bytes',allow_pickle=True)
Y_test = np.load(folder_location+'Ytest.npy',encoding='bytes',allow_pickle=True)
CA_seen = np.load(folder_location+'class_attributes_seen.npy',encoding='bytes',allow_pickle=True)
CA_unseen = np.load(folder_location+'class_attributes_unseen.npy',encoding='bytes',allow_pickle=True)

In [5]:
I = np.identity(85)

In [6]:
I_x = [0.01, 0.1, 1, 10, 20, 50, 100] #storing lambda values foriterating later

In [7]:
mu_matrix = np.zeros((50,4096))

In [8]:
for i in range(40):
  mu_matrix[i] = np.mean(X_seen[i],axis=0)

In [9]:
# W = np.zeros((85,4096))

In [10]:
np.dot(np.transpose(CA_seen),CA_seen).shape

(85, 85)

In [32]:
accu_pred_mat_dist = np.zeros(7) # for storing final accuracies
accu_pred_mat_cos_sim = np.zeros(7)

In [33]:
pred_mat_dist = np.zeros(10) # for storing the distances
pred_mat_cos_sim = np.zeros(10)

In [34]:
for l in range(7):
  W = np.linalg.inv(np.dot(np.transpose(CA_seen),CA_seen)+I_x[l]*I)
  W = np.dot(W,np.transpose(CA_seen))
  W = np.dot(W,mu_matrix[:40])

  for i in range(10):
    mu_matrix[i+40] = np.dot(CA_unseen[i],W)

  accu_pred_dist = 0 # for storing number of correctly predicted labels
  accu_pred_cos_sim = 0
  for j in range(6180):
    for i in range(10):
      pred_mat_dist[i] = np.linalg.norm(mu_matrix[i+40]-X_test[j])
      pred_mat_cos_sim[i] = np.dot(mu_matrix[i+40],X_test[j])
    if np.argmin(pred_mat_dist)+1 == Y_test[j]:
      accu_pred_dist +=1
    if np.argmax(pred_mat_cos_sim)+1 == Y_test[j]:
      accu_pred_cos_sim +=1
  accu_pred_mat_dist[l] = accu_pred_dist/61.8
  accu_pred_mat_cos_sim[l] = accu_pred_cos_sim/61.8

In [36]:
accu_pred_mat_dist,accu_pred_mat_cos_sim

(array([58.09061489, 59.54692557, 67.39482201, 73.28478964, 71.6828479 ,
        65.08090615, 56.47249191]),
 array([59.90291262, 60.12944984, 60.63106796, 55.33980583, 50.77669903,
        43.26860841, 35.61488673]))

In [39]:
print('lambda = ',I_x[np.argmax(accu_pred_mat_dist)],' gives highest accuracy ',np.max(accu_pred_mat_dist),' when using euclidean distance as metric')

lambda =  10  gives highest accuracy  73.28478964401295  when using euclidean distance as metric


In [40]:
print('lambda = ',I_x[np.argmax(accu_pred_mat_cos_sim)],' gives highest accuracy ',np.max(accu_pred_mat_cos_sim),' when using cosine similarity as metric')

lambda =  1  gives highest accuracy  60.63106796116505  when using cosine similarity as metric


In [16]:
np.unique(Y_test,return_counts=True)

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 array([701, 942, 723, 716, 608, 714, 331, 633, 303, 509]))